a=int(input("Enter a number:"))
b=int(input("Enter a number:"))
print("Addition:",a+b)
print("Subtraction:",a-b)
print("Multipication:",a*b)
print("Division:",a/b)
print("Division:",a//b)
print("Module:",a%b)
